name: Streamline Solutions Inc. CI/CD Workflow

on:
  push:
    branches:
      - test

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-dir: ~/.m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Prometheus
        run: |
          # Install Prometheus on Azure VM
          # Configure monitoring as per your requirements
          # ...

      - name: Build Docker Image
        run: docker build -t priyanshrm/spring-boot-app:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD }}

      - name: Push Docker Image
        run: docker push priyanshrm/spring-boot-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: azure-web-app-shell-java-app
          images: priyanshrm/spring-boot-app:latest

      # Add more steps for other activities
