name: Shell – Final Case Study Assessment

on:
  push:
    branches:
      - main

jobs:
  implement-ci-cd-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2

      - name: Set up JDK 17
        uses: actions/setup-java@v2.4.2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-dir: ~/.m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MAVEN_OPTS: '-Xmx3g'

      - name: Set up Prometheus
        run: |
          # Install and configure Prometheus on Azure VM
          # Commands to install and configure Prometheus
          echo "Prometheus installed and configured."

      - name: Build Docker Image
        run: docker build -t priyanshrm/shell-java-app:0.0.1.Release .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD }}

      - name: Push Docker Image
        run: docker push priyanshrm/shell-java-app:0.0.1.Release

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: azure-web-app-shell-java-app
          images: priyanshrm/shell-java-app:0.0.1.Release

      - name: Local Testing of Azure Web App
        run: |
          # Commands to locally test the deployed web app
          echo "Local testing completed."

      - name: Close Azure Boards Tasks and Sprints
        run: |
          # Commands to close tasks and sprints on Azure Boards
          echo "Tasks and sprints closed."

      - name: Project Closure and Reflection
        run: |
          # Reflect on the project's journey and document lessons learned
          echo "Project closure and reflection completed."

# Add a comment below for the outcome and rubrics
# Also, include instructions on how to review rubrics
